version: '3'

services:
  dlx_rest:
    container_name: dlx_rest
    restart: always
    build: .
    expose:
      - 8000
    command: gunicorn -w 1 -b :8000 dlx_rest.app:app
    volumes:
      - ~/.aws/:/root/.aws/:ro

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dlx_rest