services:
    dlxr:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/usr/src/app'
        expose:
            - 5000
        command: gunicorn dlx_rest.app:app --workers 3 --bind :5000 --timeout 900

    nginx:
        image: nginx
        volumes:
            - ./nginx/:/etc/nginx/conf.d
        ports:
            - "80:80"

secrets:
