name: Build and deploy to AWS Elastic Beanstalk

on:
    push:
        branches: [main, beanstalk]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            
            - name: Get pip cache dir
              id: pip-cache
              run: |
                echo "PIP_CACHE=dir::$(pip cache dir)" >> $GITHUB_OUTPUT

            - name: Cache pip
              uses: actions/cache@v4
              with:
                path: $PIP_CACHE
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-

            - name: Install dependencies
              run: 
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              run: |
                pytest