name: Build and deploy to AWS Elastic Beanstalk

on:
    push:
        branches: [main, _beanstalk]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository 
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Install dependencies
              run: 
                python -m pip install --upgrade pip &&
                python -m pip install git+https://github.com/dag-hammarskjold-library/dlx@v1.4.17 &&
                python -m pip install -r requirements-deploy.txt

            - name: Run tests
              run: |
                pytest
    deploy:
        needs:
            - build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository 
              uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Get EB CLI version
              run: |
                python -m pip install --upgrade pip
                pip install awsebcli --upgrade
                eb --version
            
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Create EBS application
              run: |
                eb init -p python-3.12 dlxr-dev --region ${{ secrets.AWS_REGION }}

            - name: Create or Update Elastic Beanstalk environment
              run: |
                (eb use test-environment && eb status test-environment && eb deploy) || eb create test-environment