name: Build and deploy to AWS Elastic Beanstalk

on:
    push:
        branches: [main, beanstalk]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install git
              run: |
                sudo apt-get update && sudo apt-get install git-all

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Cache pip
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-deploy.txt') }}
                restore-keys: |
                    ${{ runner.os }}-pip-

            - name: Install dependencies
              run: 
                python -m pip install --upgrade pip
                pip install git@https://github.com/dag-hammarskjold-library/dlx@v1.4.17
                pip install -r requirements-deploy.txt

            - name: Run tests
              run: |
                pytest